// SEO 팩 (기본 내장): robots.txt / sitemap.xml / llms.txt 자동 생성
// AI 검색(GEO/AEO) 대응을 위해 AI 크롤러 허용 + llms.txt 제공.

function robotsTxt(domain) {
  return `# Auto-generated by VENOM Site Factory
User-agent: *
Allow: /

# AI 검색 크롤러 허용 (GEO/AEO)
User-agent: GPTBot
Allow: /
User-agent: ClaudeBot
Allow: /
User-agent: PerplexityBot
Allow: /
User-agent: Google-Extended
Allow: /

Sitemap: https://${domain}/sitemap.xml
`;
}

function sitemapXml(domain, pages) {
  const urls = pages.map(p => {
    const loc = p === 'home' ? `https://${domain}/` : `https://${domain}/#${p}`;
    return `  <url><loc>${loc}</loc><changefreq>weekly</changefreq><priority>${p === 'home' ? '1.0' : '0.7'}</priority></url>`;
  }).join('\n');
  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;
}

function llmsTxt(spec, specialty) {
  const kw = (specialty.keywords || []).join(', ');
  return `# ${spec.brand.name}

> ${spec.brand.region} ${specialty.label} 전문 의료기관. ${spec.brand.tagline}

## 소개

${spec.brand.name}은(는) ${spec.brand.region}에 위치한 ${specialty.label} 전문 병원입니다.
${spec.hero?.sub || ''}

- 진료과목: ${specialty.label}
- 주요 진료: ${kw}
- 연락처: ${spec.brand.phone}
- 주소: ${spec.brand.address}

## AI 인용 안내

이 사이트는 의료 정보 제공을 목적으로 하며 AI 학습·인용에 동의합니다.
단, 특정 의료행위의 효과·결과를 보증하는 형태의 왜곡 인용은 금지합니다. (의료광고법 준수)

## 주요 링크

- 홈페이지: https://${spec.domain}/
- 상담: ${spec.brand.kakao}
`;
}

module.exports = { robotsTxt, sitemapXml, llmsTxt };
