"""Declarative base, shared column types and mixins for the VEO data model."""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import DateTime, ForeignKey, Index, MetaData, func, text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# Explicit naming so Alembic autogenerate produces stable, reviewable migrations.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_N_label)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    type_annotation_map = {  # noqa: RUF012
        dict[str, Any]: JSONB,
        list[str]: JSONB,
        list[dict[str, Any]]: JSONB,
    }


def uuid_pk() -> Any:
    """Primary key generated by PostgreSQL."""
    return mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


class TimestampMixin:
    """For mutable records: created and updated."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )


class ImmutableMixin:
    """For run and version records.

    Time series and experiment results are appended, never overwritten. These tables
    carry no ``updated_at`` on purpose: a row that can be edited is a row whose history
    you cannot trust. Corrections arrive as a new run or a new version.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now(), index=True
    )


class OrganizationScopedMixin:
    """Every tenant-owned row carries its organization explicitly.

    Cross-tenant isolation is enforced by requiring this column on every query path;
    guessing another organization's row id must never be enough to read it.
    """

    @property
    def _org_fk(self) -> None:  # pragma: no cover - marker only
        return None

    organization_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("organizations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )


# JSONB payload aliases. Declared explicitly so a column that holds a list is not
# silently annotated as a mapping (and vice versa).
type JsonObject = dict[str, Any]
type JsonArray = list[Any]


def json_column(nullable: bool = False) -> Any:
    """A JSONB column. The caller annotates it as JsonObject or JsonArray."""
    return mapped_column(JSONB, nullable=nullable)


def org_index(table_name: str, *columns: str) -> Index:
    return Index(
        f"ix_{table_name}_org_{'_'.join(columns)}",
        "organization_id",
        *columns,
    )
