"""answer documents survive a redeploy

Revision ID: 2580c21edf72
Revises: d5b2e1c9a374
Create Date: 2026-07-31 04:36:09.875791
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '2580c21edf72'
down_revision: str | None = 'd5b2e1c9a374'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer_documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('body', sa.LargeBinary(), nullable=False, comment='답변 기록의 정규 JSON 바이트. 해시는 이 바이트에 대해 계산한다.'),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_answer_documents_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answer_documents')),
    sa.UniqueConstraint('organization_id', 'object_key', name='uq_answer_documents_key')
    )
    op.create_index(op.f('ix_answer_documents_created_at'), 'answer_documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_answer_documents_organization_id'), 'answer_documents', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answer_documents_organization_id'), table_name='answer_documents')
    op.drop_index(op.f('ix_answer_documents_created_at'), table_name='answer_documents')
    op.drop_table('answer_documents')
    # ### end Alembic commands ###
