"""brand identity and run completeness

Revision ID: ce5b2b2c3f1e
Revises: 7f3c9a1d64e2
Create Date: 2026-07-28 16:08:42.042434
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'ce5b2b2c3f1e'
down_revision: str | None = '7f3c9a1d64e2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_identities',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('competitor_id', sa.UUID(), nullable=True),
    sa.Column('entity_key', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('address_terms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('phone_numbers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('distinguishing_terms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('own_domains', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('name_is_ambiguous', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], name=op.f('fk_brand_identities_competitor_id_competitors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_brand_identities_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_brand_identities_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brand_identities')),
    sa.UniqueConstraint('project_id', 'entity_key', name='uq_brand_identity_entity')
    )
    op.create_index(op.f('ix_brand_identities_organization_id'), 'brand_identities', ['organization_id'], unique=False)
    op.create_index('ix_brand_identities_project', 'brand_identities', ['project_id'], unique=False)
    op.add_column('observation_runs', sa.Column('is_complete', sa.Boolean(), nullable=False))
    op.add_column('observation_runs', sa.Column('stopped_reason', sa.String(length=48), nullable=True, comment='COMPLETED | BUDGET_EXHAUSTED | COST_UNMEASURABLE | CANCELLED | PROVIDER_UNAVAILABLE'))
    op.add_column('observation_runs', sa.Column('executions_planned', sa.Integer(), nullable=False))
    op.add_column('observation_runs', sa.Column('executions_skipped', sa.Integer(), nullable=False))
    op.add_column('observation_runs', sa.Column('prompts_below_repetition_floor', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('observation_runs', sa.Column('skipped_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('observation_runs', 'skipped_detail')
    op.drop_column('observation_runs', 'prompts_below_repetition_floor')
    op.drop_column('observation_runs', 'executions_skipped')
    op.drop_column('observation_runs', 'executions_planned')
    op.drop_column('observation_runs', 'stopped_reason')
    op.drop_column('observation_runs', 'is_complete')
    op.drop_index('ix_brand_identities_project', table_name='brand_identities')
    op.drop_index(op.f('ix_brand_identities_organization_id'), table_name='brand_identities')
    op.drop_table('brand_identities')
    # ### end Alembic commands ###
