"""initial veo schema

Revision ID: ac33acd167c5
Revises: 
Create Date: 2026-07-28 02:41:17.166561
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'ac33acd167c5'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_engines',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('provider', sa.String(length=48), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('search_mode', sa.String(length=32), nullable=False, comment='DEFAULT | WEB_SEARCH | NO_SEARCH'),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('provider_state', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_engines')),
    sa.UniqueConstraint('provider', 'model', 'search_mode', name=op.f('uq_ai_engines_provider_model_search_mode'))
    )
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('slug', name=op.f('uq_organizations_slug'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_kind', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('target_type', sa.String(length=80), nullable=True),
    sa.Column('target_id', sa.String(length=80), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('source_ip_hash', sa.String(length=64), nullable=True, comment='Hashed, never the raw address.'),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_audit_logs_organization_id_organizations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('contact_note', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_customers_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    op.create_index(op.f('ix_customers_organization_id'), 'customers', ['organization_id'], unique=False)
    op.create_table('role_assignments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], name=op.f('fk_role_assignments_granted_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_role_assignments_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_role_assignments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_assignments')),
    sa.UniqueConstraint('organization_id', 'user_id', 'role', name=op.f('uq_role_assignments_organization_id_user_id_role'))
    )
    op.create_index(op.f('ix_role_assignments_organization_id'), 'role_assignments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_role_assignments_user_id'), 'role_assignments', ['user_id'], unique=False)
    op.create_table('scoring_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('spec_id', sa.String(length=120), nullable=False),
    sa.Column('domain', sa.String(length=32), nullable=False),
    sa.Column('semantic_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('specification', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('compatible_collector_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('golden_fixture_results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_scoring_versions_approved_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scoring_versions')),
    sa.UniqueConstraint('spec_id', 'semantic_version', name=op.f('uq_scoring_versions_spec_id_semantic_version'))
    )
    op.create_index(op.f('ix_scoring_versions_checksum'), 'scoring_versions', ['checksum'], unique=False)
    op.create_index(op.f('ix_scoring_versions_created_at'), 'scoring_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_scoring_versions_spec_id'), 'scoring_versions', ['spec_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('default_seo_spec_version', sa.String(length=32), nullable=True),
    sa.Column('default_geo_spec_version', sa.String(length=32), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_projects_customer_id_customers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_projects_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('organization_id', 'slug', name=op.f('uq_projects_organization_id_slug'))
    )
    op.create_index(op.f('ix_projects_customer_id'), 'projects', ['customer_id'], unique=False)
    op.create_index(op.f('ix_projects_organization_id'), 'projects', ['organization_id'], unique=False)
    op.create_table('competitors',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('origin', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('brand_aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('selection_source', sa.String(length=32), nullable=False, comment='CUSTOMER_SPECIFIED | VEO_SUGGESTED'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_competitors_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_competitors_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competitors')),
    sa.UniqueConstraint('project_id', 'origin', name=op.f('uq_competitors_project_id_origin'))
    )
    op.create_index(op.f('ix_competitors_organization_id'), 'competitors', ['organization_id'], unique=False)
    op.create_index(op.f('ix_competitors_project_id'), 'competitors', ['project_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('surface', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('current_stage', sa.String(length=64), nullable=True),
    sa.Column('stages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scoring_spec_id', sa.String(length=120), nullable=True),
    sa.Column('scoring_spec_version', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=48), nullable=True),
    sa.Column('safe_error_message', sa.Text(), nullable=True),
    sa.Column('internal_error_ref', sa.String(length=64), nullable=True),
    sa.Column('result_run_id', sa.UUID(), nullable=True),
    sa.Column('partial_result_available', sa.Boolean(), nullable=False),
    sa.Column('estimated_cost_krw', sa.Float(), nullable=True),
    sa.Column('actual_cost_krw', sa.Float(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempts >= 0', name=op.f('ck_jobs_attempts_non_negative')),
    sa.CheckConstraint('progress >= 0 AND progress <= 1', name=op.f('ck_jobs_progress_unit_interval')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_jobs_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_jobs_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_jobs_requested_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    sa.UniqueConstraint('organization_id', 'type', 'idempotency_key', name='uq_jobs_org_type_idempotency_key')
    )
    op.create_index(op.f('ix_jobs_expires_at'), 'jobs', ['expires_at'], unique=False)
    op.create_index(op.f('ix_jobs_input_hash'), 'jobs', ['input_hash'], unique=False)
    op.create_index(op.f('ix_jobs_organization_id'), 'jobs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_jobs_project_id'), 'jobs', ['project_id'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index('ix_jobs_status_created_at', 'jobs', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_jobs_type'), 'jobs', ['type'], unique=False)
    op.create_table('keyword_lists',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_keyword_lists_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_keyword_lists_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keyword_lists')),
    sa.UniqueConstraint('project_id', 'name', name=op.f('uq_keyword_lists_project_id_name'))
    )
    op.create_index(op.f('ix_keyword_lists_organization_id'), 'keyword_lists', ['organization_id'], unique=False)
    op.create_index(op.f('ix_keyword_lists_project_id'), 'keyword_lists', ['project_id'], unique=False)
    op.create_table('prompt_sets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('generation_rule_ko', sa.Text(), nullable=True, comment='How prompts were chosen, and what was excluded and why.'),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_prompt_sets_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_prompt_sets_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_sets')),
    sa.UniqueConstraint('project_id', 'name', 'version', name=op.f('uq_prompt_sets_project_id_name_version'))
    )
    op.create_index(op.f('ix_prompt_sets_organization_id'), 'prompt_sets', ['organization_id'], unique=False)
    op.create_index(op.f('ix_prompt_sets_project_id'), 'prompt_sets', ['project_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('audience', sa.String(length=32), nullable=False, comment='BUSINESS | MARKETING | DEVELOPER — one measurement, three readings.'),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_reports_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_reports_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index(op.f('ix_reports_organization_id'), 'reports', ['organization_id'], unique=False)
    op.create_index(op.f('ix_reports_project_id'), 'reports', ['project_id'], unique=False)
    op.create_table('sites',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('origin', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('crawl_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_sites_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_sites_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sites')),
    sa.UniqueConstraint('project_id', 'origin', name=op.f('uq_sites_project_id_origin'))
    )
    op.create_index(op.f('ix_sites_organization_id'), 'sites', ['organization_id'], unique=False)
    op.create_index(op.f('ix_sites_project_id'), 'sites', ['project_id'], unique=False)
    op.create_table('api_usage_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=48), nullable=False),
    sa.Column('operation', sa.String(length=80), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('was_cache_hit', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_krw', sa.Float(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_api_usage_events_job_id_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_api_usage_events_organization_id_organizations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_api_usage_events_project_id_projects'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_usage_events'))
    )
    op.create_index(op.f('ix_api_usage_events_created_at'), 'api_usage_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_usage_events_provider'), 'api_usage_events', ['provider'], unique=False)
    op.create_index(op.f('ix_api_usage_events_request_id'), 'api_usage_events', ['request_id'], unique=False)
    op.create_index('ix_api_usage_org_provider_created', 'api_usage_events', ['organization_id', 'provider', 'created_at'], unique=False)
    op.create_table('keyword_queries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('surface', sa.String(length=16), nullable=False),
    sa.Column('original_keyword', sa.String(length=255), nullable=False),
    sa.Column('normalized_keyword', sa.String(length=255), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider_state', sa.String(length=32), nullable=False),
    sa.Column('error_code', sa.String(length=48), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_keyword_queries_job_id_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_keyword_queries_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_keyword_queries_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keyword_queries'))
    )
    op.create_index(op.f('ix_keyword_queries_created_at'), 'keyword_queries', ['created_at'], unique=False)
    op.create_index(op.f('ix_keyword_queries_normalized_keyword'), 'keyword_queries', ['normalized_keyword'], unique=False)
    op.create_index('ix_keyword_queries_org_created', 'keyword_queries', ['organization_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_keyword_queries_organization_id'), 'keyword_queries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_keyword_queries_project_id'), 'keyword_queries', ['project_id'], unique=False)
    op.create_table('observation_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('prompt_set_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('repetitions_per_prompt', sa.Integer(), nullable=False),
    sa.Column('engines', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('competitor_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('executions_attempted', sa.Integer(), nullable=False),
    sa.Column('executions_valid', sa.Integer(), nullable=False),
    sa.Column('measurement_confidence', sa.Float(), nullable=True),
    sa.Column('confidence_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_observation_runs_job_id_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_observation_runs_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_observation_runs_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_set_id'], ['prompt_sets.id'], name=op.f('fk_observation_runs_prompt_set_id_prompt_sets'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_observation_runs'))
    )
    op.create_index(op.f('ix_observation_runs_created_at'), 'observation_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_observation_runs_organization_id'), 'observation_runs', ['organization_id'], unique=False)
    op.create_index('ix_observation_runs_project_created', 'observation_runs', ['project_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_observation_runs_project_id'), 'observation_runs', ['project_id'], unique=False)
    op.create_table('prompts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('prompt_set_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=48), nullable=False),
    sa.Column('funnel', sa.String(length=48), nullable=False),
    sa.Column('persona', sa.String(length=80), nullable=True),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False, comment='BRANDED | NON_BRAND | COMPETITOR | CATEGORY'),
    sa.Column('business_importance', sa.Float(), nullable=False),
    sa.Column('expected_demand', sa.Float(), nullable=True),
    sa.Column('expected_demand_is_estimate', sa.Boolean(), nullable=False, comment='True when the demand figure is an estimate rather than measured search volume.'),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_prompts_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_set_id'], ['prompt_sets.id'], name=op.f('fk_prompts_prompt_set_id_prompt_sets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompts'))
    )
    op.create_index(op.f('ix_prompts_organization_id'), 'prompts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_prompts_prompt_set_id'), 'prompts', ['prompt_set_id'], unique=False)
    op.create_index('ix_prompts_set_intent', 'prompts', ['prompt_set_id', 'intent'], unique=False)
    op.create_table('report_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('generated_by', sa.UUID(), nullable=True),
    sa.Column('measurement_window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('measurement_window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('included_run_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scoring_versions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('disclosures_ko', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('export_formats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('public_token_hash', sa.String(length=64), nullable=True),
    sa.Column('public_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], name=op.f('fk_report_versions_generated_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_report_versions_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('fk_report_versions_report_id_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_versions')),
    sa.UniqueConstraint('report_id', 'version_number', name=op.f('uq_report_versions_report_id_version_number'))
    )
    op.create_index(op.f('ix_report_versions_created_at'), 'report_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_report_versions_organization_id'), 'report_versions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_report_versions_public_token_hash'), 'report_versions', ['public_token_hash'], unique=False)
    op.create_index(op.f('ix_report_versions_report_id'), 'report_versions', ['report_id'], unique=False)
    op.create_table('scans',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False, comment='SEO | GEO_READINESS | GEO_OBSERVATION | KEYWORD'),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('target_url', sa.Text(), nullable=True),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_scans_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_scans_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_scans_site_id_sites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scans'))
    )
    op.create_index(op.f('ix_scans_organization_id'), 'scans', ['organization_id'], unique=False)
    op.create_index(op.f('ix_scans_project_id'), 'scans', ['project_id'], unique=False)
    op.create_index(op.f('ix_scans_site_id'), 'scans', ['site_id'], unique=False)
    op.create_table('url_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('normalized_url', sa.Text(), nullable=False),
    sa.Column('original_url', sa.Text(), nullable=False),
    sa.Column('importance', sa.String(length=32), nullable=False),
    sa.Column('importance_source', sa.String(length=32), nullable=False, comment='DEFAULT | SITEMAP | INTERNAL_LINKS | TRAFFIC | USER_OVERRIDE'),
    sa.Column('click_depth', sa.Integer(), nullable=True),
    sa.Column('is_intentional_noindex', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_url_records_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_url_records_site_id_sites'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_url_records')),
    sa.UniqueConstraint('site_id', 'normalized_url', name=op.f('uq_url_records_site_id_normalized_url'))
    )
    op.create_index(op.f('ix_url_records_organization_id'), 'url_records', ['organization_id'], unique=False)
    op.create_index(op.f('ix_url_records_site_id'), 'url_records', ['site_id'], unique=False)
    op.create_table('ai_answers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('observation_run_id', sa.UUID(), nullable=False),
    sa.Column('prompt_id', sa.UUID(), nullable=False),
    sa.Column('ai_engine_id', sa.UUID(), nullable=False),
    sa.Column('repetition_index', sa.Integer(), nullable=False),
    sa.Column('model_version', sa.String(length=120), nullable=True),
    sa.Column('search_mode', sa.String(length=32), nullable=False),
    sa.Column('account_state', sa.String(length=48), nullable=True),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_valid_execution', sa.Boolean(), nullable=False),
    sa.Column('raw_answer_storage_key', sa.Text(), nullable=True),
    sa.Column('raw_answer_hash', sa.String(length=64), nullable=False),
    sa.Column('error_code', sa.String(length=48), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_krw', sa.Float(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_engine_id'], ['ai_engines.id'], name=op.f('fk_ai_answers_ai_engine_id_ai_engines'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['observation_run_id'], ['observation_runs.id'], name=op.f('fk_ai_answers_observation_run_id_observation_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_ai_answers_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], name=op.f('fk_ai_answers_prompt_id_prompts'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_answers'))
    )
    op.create_index(op.f('ix_ai_answers_created_at'), 'ai_answers', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_answers_observation_run_id'), 'ai_answers', ['observation_run_id'], unique=False)
    op.create_index(op.f('ix_ai_answers_organization_id'), 'ai_answers', ['organization_id'], unique=False)
    op.create_index('ix_ai_answers_run_prompt', 'ai_answers', ['observation_run_id', 'prompt_id'], unique=False)
    op.create_table('keyword_metrics',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('keyword_query_id', sa.UUID(), nullable=False),
    sa.Column('normalized_keyword', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('api_version', sa.String(length=32), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_period', sa.String(length=32), nullable=True),
    sa.Column('raw_response_hash', sa.String(length=64), nullable=True),
    sa.Column('was_cache_hit', sa.Boolean(), nullable=False),
    sa.Column('monthly_pc_searches', sa.Integer(), nullable=True),
    sa.Column('monthly_pc_searches_quality', sa.String(length=32), nullable=False),
    sa.Column('monthly_mobile_searches', sa.Integer(), nullable=True),
    sa.Column('monthly_mobile_searches_quality', sa.String(length=32), nullable=False),
    sa.Column('monthly_total_searches', sa.Integer(), nullable=True, comment='CALCULATED from the two device figures, not provided.'),
    sa.Column('avg_pc_clicks', sa.Float(), nullable=True),
    sa.Column('avg_mobile_clicks', sa.Float(), nullable=True),
    sa.Column('avg_pc_ctr', sa.Float(), nullable=True),
    sa.Column('avg_mobile_ctr', sa.Float(), nullable=True),
    sa.Column('competition_index', sa.Float(), nullable=True),
    sa.Column('competition_label', sa.String(length=32), nullable=True),
    sa.Column('ad_depth', sa.Integer(), nullable=True, comment='Ad slots observed. Advertising competition only.'),
    sa.Column('provider_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('partial_reason', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['keyword_query_id'], ['keyword_queries.id'], name=op.f('fk_keyword_metrics_keyword_query_id_keyword_queries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_keyword_metrics_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keyword_metrics')),
    sa.UniqueConstraint('keyword_query_id', 'normalized_keyword', name=op.f('uq_keyword_metrics_keyword_query_id_normalized_keyword'))
    )
    op.create_index(op.f('ix_keyword_metrics_created_at'), 'keyword_metrics', ['created_at'], unique=False)
    op.create_index('ix_keyword_metrics_keyword_collected', 'keyword_metrics', ['normalized_keyword', 'collected_at'], unique=False)
    op.create_index(op.f('ix_keyword_metrics_keyword_query_id'), 'keyword_metrics', ['keyword_query_id'], unique=False)
    op.create_index(op.f('ix_keyword_metrics_organization_id'), 'keyword_metrics', ['organization_id'], unique=False)
    op.create_table('keyword_opportunities',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('keyword_query_id', sa.UUID(), nullable=False),
    sa.Column('normalized_keyword', sa.String(length=255), nullable=False),
    sa.Column('formula_version', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('demand', sa.Float(), nullable=True),
    sa.Column('trend', sa.Float(), nullable=True),
    sa.Column('intent_fit', sa.Float(), nullable=True),
    sa.Column('competition_inverse', sa.Float(), nullable=True),
    sa.Column('content_gap', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('opportunity_score', sa.Float(), nullable=True),
    sa.Column('calculation_trace', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('missing_components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['keyword_query_id'], ['keyword_queries.id'], name=op.f('fk_keyword_opportunities_keyword_query_id_keyword_queries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_keyword_opportunities_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keyword_opportunities')),
    sa.UniqueConstraint('keyword_query_id', 'normalized_keyword', 'formula_version', name=op.f('uq_keyword_opportunities_keyword_query_id_normalized_keyword_formula_version'))
    )
    op.create_index(op.f('ix_keyword_opportunities_created_at'), 'keyword_opportunities', ['created_at'], unique=False)
    op.create_index(op.f('ix_keyword_opportunities_keyword_query_id'), 'keyword_opportunities', ['keyword_query_id'], unique=False)
    op.create_index(op.f('ix_keyword_opportunities_organization_id'), 'keyword_opportunities', ['organization_id'], unique=False)
    op.create_table('keyword_trends',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('keyword_query_id', sa.UUID(), nullable=False),
    sa.Column('normalized_keyword', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('time_unit', sa.String(length=16), nullable=False),
    sa.Column('device', sa.String(length=16), nullable=False),
    sa.Column('relative_index', sa.Float(), nullable=False, comment='Relative interest, 0-100 within the requested window. NOT a search count.'),
    sa.Column('index_basis_note_ko', sa.Text(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['keyword_query_id'], ['keyword_queries.id'], name=op.f('fk_keyword_trends_keyword_query_id_keyword_queries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_keyword_trends_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_keyword_trends')),
    sa.UniqueConstraint('keyword_query_id', 'normalized_keyword', 'period_start', 'device', name=op.f('uq_keyword_trends_keyword_query_id_normalized_keyword_period_start_device'))
    )
    op.create_index(op.f('ix_keyword_trends_created_at'), 'keyword_trends', ['created_at'], unique=False)
    op.create_index(op.f('ix_keyword_trends_keyword_query_id'), 'keyword_trends', ['keyword_query_id'], unique=False)
    op.create_index(op.f('ix_keyword_trends_organization_id'), 'keyword_trends', ['organization_id'], unique=False)
    op.create_table('related_keywords',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('keyword_query_id', sa.UUID(), nullable=False),
    sa.Column('seed_keyword', sa.String(length=255), nullable=False),
    sa.Column('related_keyword', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_rank', sa.Integer(), nullable=True),
    sa.Column('monthly_total_searches', sa.Integer(), nullable=True),
    sa.Column('value_quality', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['keyword_query_id'], ['keyword_queries.id'], name=op.f('fk_related_keywords_keyword_query_id_keyword_queries'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_related_keywords_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_related_keywords'))
    )
    op.create_index(op.f('ix_related_keywords_created_at'), 'related_keywords', ['created_at'], unique=False)
    op.create_index(op.f('ix_related_keywords_keyword_query_id'), 'related_keywords', ['keyword_query_id'], unique=False)
    op.create_index(op.f('ix_related_keywords_organization_id'), 'related_keywords', ['organization_id'], unique=False)
    op.create_index('ix_related_keywords_query_rank', 'related_keywords', ['keyword_query_id', 'source_rank'], unique=False)
    op.create_table('scan_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('surface', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collector_version', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('device_profile', sa.String(length=16), nullable=False),
    sa.Column('urls_attempted', sa.Integer(), nullable=False),
    sa.Column('urls_collected', sa.Integer(), nullable=False),
    sa.Column('provider_states', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('partial_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_scan_runs_job_id_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_scan_runs_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], name=op.f('fk_scan_runs_scan_id_scans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_runs'))
    )
    op.create_index(op.f('ix_scan_runs_created_at'), 'scan_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_scan_runs_expires_at'), 'scan_runs', ['expires_at'], unique=False)
    op.create_index(op.f('ix_scan_runs_job_id'), 'scan_runs', ['job_id'], unique=False)
    op.create_index(op.f('ix_scan_runs_organization_id'), 'scan_runs', ['organization_id'], unique=False)
    op.create_index('ix_scan_runs_scan_created', 'scan_runs', ['scan_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_scan_runs_scan_id'), 'scan_runs', ['scan_id'], unique=False)
    op.create_table('check_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('scan_run_id', sa.UUID(), nullable=False),
    sa.Column('url_record_id', sa.UUID(), nullable=True),
    sa.Column('check_id', sa.String(length=120), nullable=False),
    sa.Column('category_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='PASS | WARNING | FAIL | NOT_APPLICABLE | UNKNOWN'),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('affected_weight', sa.Float(), nullable=False),
    sa.Column('evaluated_weight', sa.Float(), nullable=False),
    sa.Column('not_applicable_reason', sa.Text(), nullable=True),
    sa.Column('unknown_reason', sa.Text(), nullable=True),
    sa.Column('observed_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('affected_weight <= evaluated_weight', name=op.f('ck_check_results_affected_within_evaluated')),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_check_results_confidence_unit_interval')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_check_results_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.id'], name=op.f('fk_check_results_scan_run_id_scan_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['url_record_id'], ['url_records.id'], name=op.f('fk_check_results_url_record_id_url_records'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_check_results'))
    )
    op.create_index(op.f('ix_check_results_check_id'), 'check_results', ['check_id'], unique=False)
    op.create_index(op.f('ix_check_results_created_at'), 'check_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_check_results_organization_id'), 'check_results', ['organization_id'], unique=False)
    op.create_index('ix_check_results_run_check', 'check_results', ['scan_run_id', 'check_id'], unique=False)
    op.create_index(op.f('ix_check_results_scan_run_id'), 'check_results', ['scan_run_id'], unique=False)
    op.create_table('citations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ai_answer_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('is_own_domain', sa.Boolean(), nullable=False),
    sa.Column('competitor_id', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_answer_id'], ['ai_answers.id'], name=op.f('fk_citations_ai_answer_id_ai_answers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], name=op.f('fk_citations_competitor_id_competitors'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_citations_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_citations'))
    )
    op.create_index(op.f('ix_citations_ai_answer_id'), 'citations', ['ai_answer_id'], unique=False)
    op.create_index('ix_citations_answer_domain', 'citations', ['ai_answer_id', 'domain'], unique=False)
    op.create_index(op.f('ix_citations_created_at'), 'citations', ['created_at'], unique=False)
    op.create_index(op.f('ix_citations_organization_id'), 'citations', ['organization_id'], unique=False)
    op.create_table('entity_mentions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ai_answer_id', sa.UUID(), nullable=False),
    sa.Column('entity_key', sa.String(length=200), nullable=False),
    sa.Column('is_own_brand', sa.Boolean(), nullable=False),
    sa.Column('competitor_id', sa.UUID(), nullable=True),
    sa.Column('raw_occurrence_count', sa.Integer(), nullable=False),
    sa.Column('first_position', sa.Integer(), nullable=True),
    sa.Column('sentiment', sa.String(length=16), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=False),
    sa.Column('needs_human_disambiguation', sa.Boolean(), nullable=False, comment='Same-name brands go to a manual queue rather than being guessed.'),
    sa.Column('review_state', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_answer_id'], ['ai_answers.id'], name=op.f('fk_entity_mentions_ai_answer_id_ai_answers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], name=op.f('fk_entity_mentions_competitor_id_competitors'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_entity_mentions_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_mentions')),
    sa.UniqueConstraint('ai_answer_id', 'entity_key', name=op.f('uq_entity_mentions_ai_answer_id_entity_key'))
    )
    op.create_index(op.f('ix_entity_mentions_ai_answer_id'), 'entity_mentions', ['ai_answer_id'], unique=False)
    op.create_index(op.f('ix_entity_mentions_created_at'), 'entity_mentions', ['created_at'], unique=False)
    op.create_index(op.f('ix_entity_mentions_organization_id'), 'entity_mentions', ['organization_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('scan_run_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=48), nullable=False, comment='http_response | raw_html | rendered_dom | robots_txt | sitemap_document | lighthouse_run | crux_record | provider_response | screenshot | external_source'),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=True, comment='Object storage key for large payloads.'),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=48), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_evidence_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.id'], name=op.f('fk_evidence_scan_run_id_scan_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence'))
    )
    op.create_index(op.f('ix_evidence_content_hash'), 'evidence', ['content_hash'], unique=False)
    op.create_index(op.f('ix_evidence_created_at'), 'evidence', ['created_at'], unique=False)
    op.create_index(op.f('ix_evidence_organization_id'), 'evidence', ['organization_id'], unique=False)
    op.create_index('ix_evidence_run_kind', 'evidence', ['scan_run_id', 'kind'], unique=False)
    op.create_index(op.f('ix_evidence_scan_run_id'), 'evidence', ['scan_run_id'], unique=False)
    op.create_table('issues',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('first_seen_run_id', sa.UUID(), nullable=True),
    sa.Column('last_seen_run_id', sa.UUID(), nullable=True),
    sa.Column('check_id', sa.String(length=120), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('title_ko', sa.Text(), nullable=False),
    sa.Column('business_impact_ko', sa.Text(), nullable=True),
    sa.Column('affected_url_count', sa.Integer(), nullable=False),
    sa.Column('sample_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('remediation_owner', sa.String(length=32), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('regression_count', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_issues_assigned_to_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['first_seen_run_id'], ['scan_runs.id'], name=op.f('fk_issues_first_seen_run_id_scan_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_seen_run_id'], ['scan_runs.id'], name=op.f('fk_issues_last_seen_run_id_scan_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_issues_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_issues_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_issues'))
    )
    op.create_index(op.f('ix_issues_check_id'), 'issues', ['check_id'], unique=False)
    op.create_index(op.f('ix_issues_organization_id'), 'issues', ['organization_id'], unique=False)
    op.create_index(op.f('ix_issues_project_id'), 'issues', ['project_id'], unique=False)
    op.create_index('ix_issues_project_state', 'issues', ['project_id', 'state'], unique=False)
    op.create_table('score_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('scan_run_id', sa.UUID(), nullable=False),
    sa.Column('spec_id', sa.String(length=120), nullable=False),
    sa.Column('spec_version', sa.String(length=32), nullable=False),
    sa.Column('spec_checksum', sa.String(length=64), nullable=False),
    sa.Column('domain', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('score_before_caps', sa.Float(), nullable=True),
    sa.Column('band_id', sa.String(length=32), nullable=True),
    sa.Column('coverage', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('effective_weight_total', sa.Float(), nullable=False),
    sa.Column('category_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('applied_caps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('calculation_trace', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recomputed_from_score_result_id', sa.UUID(), nullable=True, comment='Set when an older run was re-scored under a newer spec. Both rows survive.'),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_score_results_confidence_unit_interval')),
    sa.CheckConstraint('coverage >= 0 AND coverage <= 1', name=op.f('ck_score_results_coverage_unit_interval')),
    sa.CheckConstraint('score IS NULL OR (score >= 0 AND score <= 100)', name=op.f('ck_score_results_score_range')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_score_results_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recomputed_from_score_result_id'], ['score_results.id'], name=op.f('fk_score_results_recomputed_from_score_result_id_score_results'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.id'], name=op.f('fk_score_results_scan_run_id_scan_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_score_results')),
    sa.UniqueConstraint('scan_run_id', 'spec_id', 'spec_version', name=op.f('uq_score_results_scan_run_id_spec_id_spec_version'))
    )
    op.create_index(op.f('ix_score_results_created_at'), 'score_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_score_results_organization_id'), 'score_results', ['organization_id'], unique=False)
    op.create_index(op.f('ix_score_results_scan_run_id'), 'score_results', ['scan_run_id'], unique=False)
    op.create_table('claim_assessments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ai_answer_id', sa.UUID(), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('assessment_type', sa.String(length=48), nullable=False, comment='CLAIM_ACCURACY | CITATION_ENTAILMENT | CITATION_COMPLETENESS | ENTITY_DISAMBIGUATION | RECOMMENDATION | SENTIMENT | STALENESS'),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('automated_verdict', sa.String(length=32), nullable=False),
    sa.Column('automated_rationale', sa.Text(), nullable=True),
    sa.Column('llm_model', sa.String(length=120), nullable=True),
    sa.Column('llm_prompt_version', sa.String(length=64), nullable=True),
    sa.Column('review_state', sa.String(length=32), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewer_note', sa.Text(), nullable=True),
    sa.Column('supporting_citation_id', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ai_answer_id'], ['ai_answers.id'], name=op.f('fk_claim_assessments_ai_answer_id_ai_answers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_claim_assessments_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_claim_assessments_reviewed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supporting_citation_id'], ['citations.id'], name=op.f('fk_claim_assessments_supporting_citation_id_citations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim_assessments'))
    )
    op.create_index(op.f('ix_claim_assessments_ai_answer_id'), 'claim_assessments', ['ai_answer_id'], unique=False)
    op.create_index(op.f('ix_claim_assessments_organization_id'), 'claim_assessments', ['organization_id'], unique=False)
    op.create_table('fix_recommendations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('issue_id', sa.UUID(), nullable=False),
    sa.Column('summary_ko', sa.Text(), nullable=False),
    sa.Column('developer_steps_ko', sa.Text(), nullable=True),
    sa.Column('code_example', sa.Text(), nullable=True),
    sa.Column('estimated_effort', sa.String(length=32), nullable=True),
    sa.Column('reverification_rule', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_by', sa.String(length=32), nullable=False, comment='RULE | LLM_ASSISTED | HUMAN — an LLM may explain a fix, never decide a score.'),
    sa.Column('llm_prompt_version', sa.String(length=64), nullable=True),
    sa.Column('review_state', sa.String(length=32), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], name=op.f('fk_fix_recommendations_issue_id_issues'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_fix_recommendations_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fix_recommendations'))
    )
    op.create_index(op.f('ix_fix_recommendations_issue_id'), 'fix_recommendations', ['issue_id'], unique=False)
    op.create_index(op.f('ix_fix_recommendations_organization_id'), 'fix_recommendations', ['organization_id'], unique=False)
    op.create_table('verification_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('issue_id', sa.UUID(), nullable=False),
    sa.Column('scan_run_id', sa.UUID(), nullable=True),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=False, comment='RESOLVED | STILL_FAILING | INCONCLUSIVE'),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], name=op.f('fk_verification_runs_issue_id_issues'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_verification_runs_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_verification_runs_requested_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scan_run_id'], ['scan_runs.id'], name=op.f('fk_verification_runs_scan_run_id_scan_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_runs'))
    )
    op.create_index(op.f('ix_verification_runs_created_at'), 'verification_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_verification_runs_issue_id'), 'verification_runs', ['issue_id'], unique=False)
    op.create_index(op.f('ix_verification_runs_organization_id'), 'verification_runs', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_runs_organization_id'), table_name='verification_runs')
    op.drop_index(op.f('ix_verification_runs_issue_id'), table_name='verification_runs')
    op.drop_index(op.f('ix_verification_runs_created_at'), table_name='verification_runs')
    op.drop_table('verification_runs')
    op.drop_index(op.f('ix_fix_recommendations_organization_id'), table_name='fix_recommendations')
    op.drop_index(op.f('ix_fix_recommendations_issue_id'), table_name='fix_recommendations')
    op.drop_table('fix_recommendations')
    op.drop_index(op.f('ix_claim_assessments_organization_id'), table_name='claim_assessments')
    op.drop_index(op.f('ix_claim_assessments_ai_answer_id'), table_name='claim_assessments')
    op.drop_table('claim_assessments')
    op.drop_index(op.f('ix_score_results_scan_run_id'), table_name='score_results')
    op.drop_index(op.f('ix_score_results_organization_id'), table_name='score_results')
    op.drop_index(op.f('ix_score_results_created_at'), table_name='score_results')
    op.drop_table('score_results')
    op.drop_index('ix_issues_project_state', table_name='issues')
    op.drop_index(op.f('ix_issues_project_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_organization_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_check_id'), table_name='issues')
    op.drop_table('issues')
    op.drop_index(op.f('ix_evidence_scan_run_id'), table_name='evidence')
    op.drop_index('ix_evidence_run_kind', table_name='evidence')
    op.drop_index(op.f('ix_evidence_organization_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_created_at'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_content_hash'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_entity_mentions_organization_id'), table_name='entity_mentions')
    op.drop_index(op.f('ix_entity_mentions_created_at'), table_name='entity_mentions')
    op.drop_index(op.f('ix_entity_mentions_ai_answer_id'), table_name='entity_mentions')
    op.drop_table('entity_mentions')
    op.drop_index(op.f('ix_citations_organization_id'), table_name='citations')
    op.drop_index(op.f('ix_citations_created_at'), table_name='citations')
    op.drop_index('ix_citations_answer_domain', table_name='citations')
    op.drop_index(op.f('ix_citations_ai_answer_id'), table_name='citations')
    op.drop_table('citations')
    op.drop_index(op.f('ix_check_results_scan_run_id'), table_name='check_results')
    op.drop_index('ix_check_results_run_check', table_name='check_results')
    op.drop_index(op.f('ix_check_results_organization_id'), table_name='check_results')
    op.drop_index(op.f('ix_check_results_created_at'), table_name='check_results')
    op.drop_index(op.f('ix_check_results_check_id'), table_name='check_results')
    op.drop_table('check_results')
    op.drop_index(op.f('ix_scan_runs_scan_id'), table_name='scan_runs')
    op.drop_index('ix_scan_runs_scan_created', table_name='scan_runs')
    op.drop_index(op.f('ix_scan_runs_organization_id'), table_name='scan_runs')
    op.drop_index(op.f('ix_scan_runs_job_id'), table_name='scan_runs')
    op.drop_index(op.f('ix_scan_runs_expires_at'), table_name='scan_runs')
    op.drop_index(op.f('ix_scan_runs_created_at'), table_name='scan_runs')
    op.drop_table('scan_runs')
    op.drop_index('ix_related_keywords_query_rank', table_name='related_keywords')
    op.drop_index(op.f('ix_related_keywords_organization_id'), table_name='related_keywords')
    op.drop_index(op.f('ix_related_keywords_keyword_query_id'), table_name='related_keywords')
    op.drop_index(op.f('ix_related_keywords_created_at'), table_name='related_keywords')
    op.drop_table('related_keywords')
    op.drop_index(op.f('ix_keyword_trends_organization_id'), table_name='keyword_trends')
    op.drop_index(op.f('ix_keyword_trends_keyword_query_id'), table_name='keyword_trends')
    op.drop_index(op.f('ix_keyword_trends_created_at'), table_name='keyword_trends')
    op.drop_table('keyword_trends')
    op.drop_index(op.f('ix_keyword_opportunities_organization_id'), table_name='keyword_opportunities')
    op.drop_index(op.f('ix_keyword_opportunities_keyword_query_id'), table_name='keyword_opportunities')
    op.drop_index(op.f('ix_keyword_opportunities_created_at'), table_name='keyword_opportunities')
    op.drop_table('keyword_opportunities')
    op.drop_index(op.f('ix_keyword_metrics_organization_id'), table_name='keyword_metrics')
    op.drop_index(op.f('ix_keyword_metrics_keyword_query_id'), table_name='keyword_metrics')
    op.drop_index('ix_keyword_metrics_keyword_collected', table_name='keyword_metrics')
    op.drop_index(op.f('ix_keyword_metrics_created_at'), table_name='keyword_metrics')
    op.drop_table('keyword_metrics')
    op.drop_index('ix_ai_answers_run_prompt', table_name='ai_answers')
    op.drop_index(op.f('ix_ai_answers_organization_id'), table_name='ai_answers')
    op.drop_index(op.f('ix_ai_answers_observation_run_id'), table_name='ai_answers')
    op.drop_index(op.f('ix_ai_answers_created_at'), table_name='ai_answers')
    op.drop_table('ai_answers')
    op.drop_index(op.f('ix_url_records_site_id'), table_name='url_records')
    op.drop_index(op.f('ix_url_records_organization_id'), table_name='url_records')
    op.drop_table('url_records')
    op.drop_index(op.f('ix_scans_site_id'), table_name='scans')
    op.drop_index(op.f('ix_scans_project_id'), table_name='scans')
    op.drop_index(op.f('ix_scans_organization_id'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_report_versions_report_id'), table_name='report_versions')
    op.drop_index(op.f('ix_report_versions_public_token_hash'), table_name='report_versions')
    op.drop_index(op.f('ix_report_versions_organization_id'), table_name='report_versions')
    op.drop_index(op.f('ix_report_versions_created_at'), table_name='report_versions')
    op.drop_table('report_versions')
    op.drop_index('ix_prompts_set_intent', table_name='prompts')
    op.drop_index(op.f('ix_prompts_prompt_set_id'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_organization_id'), table_name='prompts')
    op.drop_table('prompts')
    op.drop_index(op.f('ix_observation_runs_project_id'), table_name='observation_runs')
    op.drop_index('ix_observation_runs_project_created', table_name='observation_runs')
    op.drop_index(op.f('ix_observation_runs_organization_id'), table_name='observation_runs')
    op.drop_index(op.f('ix_observation_runs_created_at'), table_name='observation_runs')
    op.drop_table('observation_runs')
    op.drop_index(op.f('ix_keyword_queries_project_id'), table_name='keyword_queries')
    op.drop_index(op.f('ix_keyword_queries_organization_id'), table_name='keyword_queries')
    op.drop_index('ix_keyword_queries_org_created', table_name='keyword_queries')
    op.drop_index(op.f('ix_keyword_queries_normalized_keyword'), table_name='keyword_queries')
    op.drop_index(op.f('ix_keyword_queries_created_at'), table_name='keyword_queries')
    op.drop_table('keyword_queries')
    op.drop_index('ix_api_usage_org_provider_created', table_name='api_usage_events')
    op.drop_index(op.f('ix_api_usage_events_request_id'), table_name='api_usage_events')
    op.drop_index(op.f('ix_api_usage_events_provider'), table_name='api_usage_events')
    op.drop_index(op.f('ix_api_usage_events_created_at'), table_name='api_usage_events')
    op.drop_table('api_usage_events')
    op.drop_index(op.f('ix_sites_project_id'), table_name='sites')
    op.drop_index(op.f('ix_sites_organization_id'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_reports_project_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_organization_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_prompt_sets_project_id'), table_name='prompt_sets')
    op.drop_index(op.f('ix_prompt_sets_organization_id'), table_name='prompt_sets')
    op.drop_table('prompt_sets')
    op.drop_index(op.f('ix_keyword_lists_project_id'), table_name='keyword_lists')
    op.drop_index(op.f('ix_keyword_lists_organization_id'), table_name='keyword_lists')
    op.drop_table('keyword_lists')
    op.drop_index(op.f('ix_jobs_type'), table_name='jobs')
    op.drop_index('ix_jobs_status_created_at', table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_project_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_organization_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_input_hash'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_expires_at'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_competitors_project_id'), table_name='competitors')
    op.drop_index(op.f('ix_competitors_organization_id'), table_name='competitors')
    op.drop_table('competitors')
    op.drop_index(op.f('ix_projects_organization_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_customer_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_scoring_versions_spec_id'), table_name='scoring_versions')
    op.drop_index(op.f('ix_scoring_versions_created_at'), table_name='scoring_versions')
    op.drop_index(op.f('ix_scoring_versions_checksum'), table_name='scoring_versions')
    op.drop_table('scoring_versions')
    op.drop_index(op.f('ix_role_assignments_user_id'), table_name='role_assignments')
    op.drop_index(op.f('ix_role_assignments_organization_id'), table_name='role_assignments')
    op.drop_table('role_assignments')
    op.drop_index(op.f('ix_customers_organization_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('organizations')
    op.drop_table('ai_engines')
    # ### end Alembic commands ###
