"""scan run report snapshot and actor

Revision ID: 87dbf72e5649
Revises: 29733eb876f1
Create Date: 2026-07-29 16:56:25.639194
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '87dbf72e5649'
down_revision: str | None = '29733eb876f1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_runs', sa.Column('requested_by_user_id', sa.UUID(), nullable=True, comment='진단을 실행한 사용자. 예약 실행이면 NULL.'))
    op.add_column('scan_runs', sa.Column('report_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='그때 반환한 ScanPayload 전문.'))
    op.create_foreign_key(op.f('fk_scan_runs_requested_by_user_id_users'), 'scan_runs', 'users', ['requested_by_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_scan_runs_requested_by_user_id_users'), 'scan_runs', type_='foreignkey')
    op.drop_column('scan_runs', 'report_snapshot')
    op.drop_column('scan_runs', 'requested_by_user_id')
    # ### end Alembic commands ###
